In [2]:
# ============================================================
# INTERMEDIATE NUMPY EXERCISE
# ============================================================

import numpy as np

print("--- Intermediate NumPy Exercise ---")
print("Complete each task by writing the requested NumPy code.")
print("-----------------------------------")


# ============================================================
# TASK 1: ARRAY CREATION SHORTCUTS
# ============================================================

print("\n--- Task 1: Array Creation Shortcuts ---")

# 1.1 Create a 1D array from 0 to 99
arr1_1 = np.arange(100)

# 1.2 Create a 3x3 array filled with ones
arr1_2 = np.ones((3, 3))

# 1.3 Create a 2x4 array filled with 7
arr1_3 = np.full((2, 4), 7)

# 1.4 Create a 5x5 array with random integers from 10 to 50
arr1_4 = np.random.randint(10, 51, size=(5, 5))

print("arr1_1 (first 10 elements):", arr1_1[:10])
print("arr1_2:\n", arr1_2)
print("arr1_3:\n", arr1_3)
print("arr1_4 (first 2 rows):\n", arr1_4[:2])


# ============================================================
# TASK 2: INDEXING AND SLICING WITH ARRAYS
# ============================================================

print("\n--- Task 2: Indexing and Slicing with Arrays ---")

data = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120],
    [130, 140, 150, 160]
])

# 2.1 Extract element at row 2, column 3
val2_1 = data[2, 3]

# 2.2 Extract the first row
row2_2 = data[0, :]

# 2.3 Extract the last column
col2_3 = data[:, -1]

# 2.4 Extract rows 1 and 2, columns 0 and 1
sub_arr2_4 = data[1:3, 0:2]

# 2.5 Select all elements greater than 100
filtered_elements2_5 = data[data > 100]

print("Element at row 2, column 3:", val2_1)
print("First row:", row2_2)
print("Last column:", col2_3)
print("Sub-array:\n", sub_arr2_4)
print("Elements greater than 100:", filtered_elements2_5)


# ============================================================
# TASK 3: CONDITIONAL OPERATIONS
# ============================================================

print("\n--- Task 3: Conditional Operations ---")

arr3_1 = np.random.randint(1, 21, size=(4, 5))

# 3.1 Replace elements less than 10 with 0
arr3_2 = np.where(arr3_1 < 10, 0, arr3_1)

# 3.2 Count even elements
even_count3_3 = np.sum(arr3_1 % 2 == 0)

print("arr3_1:\n", arr3_1)
print("arr3_2:\n", arr3_2)
print("Number of even elements:", even_count3_3)


# ============================================================
# TASK 4: AGGREGATION FUNCTIONS
# ============================================================

print("\n--- Task 4: Aggregation Functions ---")

arr4_1 = np.array([
    [10, 5, 12],
    [3, 8, 15],
    [20, 7, 4]
])

# 4.1 Sum of all elements
sum4_1 = np.sum(arr4_1)

# 4.2 Mean of each column
mean_cols4_2 = np.mean(arr4_1, axis=0)

# 4.3 Maximum value in each row
max_rows4_3 = np.max(arr4_1, axis=1)

# 4.4 Standard deviation of the entire array
std4_4 = np.std(arr4_1)

print("Sum:", sum4_1)
print("Mean of each column:", mean_cols4_2)
print("Maximum of each row:", max_rows4_3)
print("Standard deviation:", std4_4)


# ============================================================
# TASK 5: RESHAPING AND FLATTENING
# ============================================================

print("\n--- Task 5: Reshaping and Flattening ---")

arr5_1 = np.arange(24)

# 5.1 Reshape into 4x6
reshaped_arr5_2 = arr5_1.reshape(4, 6)

# 5.2 Reshape into 2x3x4
reshaped_arr5_3 = arr5_1.reshape(2, 3, 4)

# 5.3 Flatten using ravel()
flattened_arr5_4 = reshaped_arr5_2.ravel()

# Also flatten using flatten()
flattened_arr5_4_flatten = reshaped_arr5_2.flatten()

print("Original array:", arr5_1)
print("4x6 array:\n", reshaped_arr5_2)
print("2x3x4 array:\n", reshaped_arr5_3)
print("Using ravel():", flattened_arr5_4)
print("Using flatten():", flattened_arr5_4_flatten)


# ============================================================
# TASK 6: BROADCASTING
# ============================================================

print("\n--- Task 6: Broadcasting ---")

arr6_1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

scalar = 10
vector = np.array([100, 200, 300])

# 6.1 Add scalar to every element
result6_1 = arr6_1 + scalar

# 6.2 Add vector to each row
result6_2 = arr6_1 + vector

print("Original array:\n", arr6_1)
print("After adding scalar:\n", result6_1)
print("After adding vector:\n", result6_2)


# ============================================================
# TASK 7: COPYING VS. VIEWING ARRAYS
# ============================================================

print("\n--- Task 7: Copying vs. Viewing Arrays ---")

original_arr7 = np.array([1, 2, 3, 4, 5])

# 7.1 Create a view using slicing
view_arr7 = original_arr7[:]

# Modify the first element of the view
view_arr7[0] = 99

print("View array:", view_arr7)
print("Original array after modifying view:", original_arr7)

# 7.2 Create a copy
copy_arr7 = original_arr7.copy()

# Modify the last element of the copy
copy_arr7[-1] = 0

print("Copy array:", copy_arr7)
print("Original array after modifying copy:", original_arr7)


# ============================================================
# TASK 8: STACKING AND SPLITTING ARRAYS
# ============================================================

print("\n--- Task 8: Stacking and Splitting Arrays ---")

arr8_a = np.array([
    [1, 2],
    [3, 4]
])

arr8_b = np.array([
    [5, 6],
    [7, 8]
])

arr8_c = np.array([
    [9, 10]
])

# 8.1 Vertically stack arr8_a and arr8_b
vstack_arr8_1 = np.vstack((arr8_a, arr8_b))

# 8.2 Horizontally stack arr8_a and arr8_b
hstack_arr8_2 = np.hstack((arr8_a, arr8_b))

# 8.3 Vertically stack vstack_arr8_1 and arr8_c
combined_arr8_3 = np.vstack((vstack_arr8_1, arr8_c))

# 8.4 Split into 3 nearly equal parts
# np.vsplit() cannot divide 5 rows equally into 3 parts.
# Therefore, np.array_split() is used.
part1, part2, part3 = np.array_split(combined_arr8_3, 3)

print("Vertical stack:\n", vstack_arr8_1)
print("Horizontal stack:\n", hstack_arr8_2)
print("Combined array:\n", combined_arr8_3)

print("Part 1:\n", part1)
print("Part 2:\n", part2)
print("Part 3:\n", part3)


# ============================================================
# TASK 9: SORTING AND SEARCHING
# ============================================================

print("\n--- Task 9: Sorting and Searching ---")

arr9_1 = np.array([
    5, 2, 8, 1, 9, 4, 7, 3, 6
])

arr9_2d = np.array([
    [30, 20, 10],
    [60, 50, 40],
    [90, 80, 70]
])

# 9.1 Sort arr9_1 in ascending order
sorted_arr9_1 = np.sort(arr9_1)

# 9.2 Sort arr9_2d along columns
sorted_cols9_2 = np.sort(arr9_2d, axis=0)

# 9.3 Find index where value 9 is present
idx9_3 = np.where(arr9_1 == 9)

# 9.4 Find index of maximum value
max_idx9_4 = np.argmax(arr9_1)

print("Sorted arr9_1:", sorted_arr9_1)
print("Sorted columns:\n", sorted_cols9_2)
print("Index of value 9:", idx9_3)
print("Index of maximum value:", max_idx9_4)

--- Intermediate NumPy Exercise ---
Complete each task by writing the requested NumPy code.
-----------------------------------

--- Task 1: Array Creation Shortcuts ---
arr1_1 (first 10 elements): [0 1 2 3 4 5 6 7 8 9]
arr1_2:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
arr1_3:
 [[7 7 7 7]
 [7 7 7 7]]
arr1_4 (first 2 rows):
 [[31 37 10 25 11]
 [37 44 29 13 31]]

--- Task 2: Indexing and Slicing with Arrays ---
Element at row 2, column 3: 120
First row: [10 20 30 40]
Last column: [ 40  80 120 160]
Sub-array:
 [[ 50  60]
 [ 90 100]]
Elements greater than 100: [110 120 130 140 150 160]

--- Task 3: Conditional Operations ---
arr3_1:
 [[ 2  5 20  5  1]
 [12 19  1  7 16]
 [11  8 15 15 16]
 [18  8 11  4  7]]
arr3_2:
 [[ 0  0 20  0  0]
 [12 19  0  0 16]
 [11  0 15 15 16]
 [18  0 11  0  0]]
Number of even elements: 9

--- Task 4: Aggregation Functions ---
Sum: 84
Mean of each column: [11.          6.66666667 10.33333333]
Maximum of each row: [12 15 20]
Standard deviation: 5.2493385826745405

--- Ta